version: '3.3'

services:
  postgres.warehouse-service:
    image: postgres:13.2
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: warehouse
    ports:
      - '5435:5432'
    restart: always
    volumes:
      - warehouse_postgres_data:/var/lib/postgresql/data

  postgres.warehouse-service.test:
    image: postgres:13.2
    environment:
      POSTGRES_USER: warehouse_user_test
      POSTGRES_PASSWORD: warehouse_password_test
      POSTGRES_DB: warehouse_test
    ports:
      - '5440:5432'
    restart: always

  postgres.customer-service:
    image: postgres:13.2
    environment:
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_password
      POSTGRES_DB: customer
    ports:
      - '5436:5432'
    restart: always
    volumes:
      - customer_postgres_data:/var/lib/postgresql/data

  postgres.customer-service.test:
    image: postgres:13.2
    environment:
      POSTGRES_USER: customer_user_test
      POSTGRES_PASSWORD: customer_password_test
      POSTGRES_DB: customer_test
    ports:
      - '5438:5432'
    restart: always

  postgres.order-processor-service:
    image: postgres:13.2
    environment:
      POSTGRES_USER: order_processor_user
      POSTGRES_PASSWORD: order_processor_password
      POSTGRES_DB: order_processor
    ports:
      - '5437:5432'
    restart: always
    volumes:
      - order_processor_postgres_data:/var/lib/postgresql/data

  postgres.order-processor-service.test:
    image: postgres:13.2
    environment:
      POSTGRES_USER: order_processor_user_test
      POSTGRES_PASSWORD: order_processor_password_test
      POSTGRES_DB: order_processor_test
    ports:
      - '5439:5432'
    restart: always

  mongo:
    image: mongo:4.4.15
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: icommerce
      MONGO_INITDB_ROOT_USERNAME: icommerce
      MONGO_INITDB_ROOT_PASSWORD: icommerce
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: icommerce
      ME_CONFIG_MONGODB_ADMINPASSWORD: icommerce
      ME_CONFIG_MONGODB_URL: mongodb://icommerce:icommerce@mongo:27017/
    depends_on:
      - mongo

  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.10
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=icommerce
      - RABBITMQ_PASSWORD=icommerce
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.8
      - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=5GB
    restart: always
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'

volumes:
  mongo_data:
  mongo_config:
  rabbitmq_data:
  warehouse_postgres_data:
  customer_postgres_data:
  order_processor_postgres_data:
